Repository Moms-Nagging-Org/MomsNaggingAPI, pull requests merged in 2022-08, with the labels that each got.

#84 습관의 남은 건너뜀 횟수 조회 API 추가
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/controller/ScheduleController.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
Labels: documentation, enhancement

#87 75 [feature] 관리자 API 작성
  src/main/java/com/jasik/momsnaggingapi/domain/admin/controller/AdminController.java
  src/main/java/com/jasik/momsnaggingapi/domain/admin/service/AdminService.java
  src/main/java/com/jasik/momsnaggingapi/domain/nagging/Nagging.java
  src/main/java/com/jasik/momsnaggingapi/domain/nagging/repository/NaggingRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/push/Push.java
  src/main/java/com/jasik/momsnaggingapi/domain/push/repository/PushRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/push/service/FCMService.java
  src/main/java/com/jasik/momsnaggingapi/domain/push/service/PushService.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
Labels: documentation, enhancement

#89 88 [:bug:] 스케줄 리스트 조회 시 원본 스케줄 Id 미포함
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
Labels: bug

#91 90 [:bug:] n회 반복 습관 삭제 에러 수정
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
Labels: bug

#94 93 [:bug:] Push 알림 발송 안됨
  src/main/java/com/jasik/momsnaggingapi/MomsNaggingApiApplication.java
Labels: bug

#96 95 [:bug:] N회 반복 습관 생성 시 일주일 전부 생성 안됨
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
Labels: bug

#98 97 [feature] Push 알림 잔소리에 닉네임 추가
  src/main/java/com/jasik/momsnaggingapi/domain/push/service/FCMService.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
Labels: enhancement

#100 99 [feature] 추천 습관 조회 시 잔소리 ID 컬럼 추가
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
Labels: enhancement

#102 101 [feature] admin API pagenation 적용
  src/main/java/com/jasik/momsnaggingapi/domain/admin/Admin.java
  src/main/java/com/jasik/momsnaggingapi/domain/admin/controller/AdminController.java
  src/main/java/com/jasik/momsnaggingapi/domain/admin/service/AdminService.java
  src/main/java/com/jasik/momsnaggingapi/domain/question/Question.java
  src/main/java/com/jasik/momsnaggingapi/domain/question/repository/QuestionRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/question/service/QuestionService.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/User.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/repository/UserRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/service/UserService.java
Labels: enhancement

#103 92 [:bug:] 습관 수정 시 간헐적으로 중복 생성됨
  src/main/java/com/jasik/momsnaggingapi/domain/push/service/FCMService.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
Labels: bug

#105 104 [:bug:] 요일 반복 습관 <-> N회 반복 습관 수정 안됨
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
Labels: bug
