Repository Moms-Nagging-Org/MomsNaggingAPI, pull requests merged in 2022-05, with the labels that each got.

#34 #28 Schedule API Docs 작성 완료
  src/main/java/com/jasik/momsnaggingapi/MomsNaggingApiApplication.java
  src/main/java/com/jasik/momsnaggingapi/domain/appVersion/AppVersion.java
  src/main/java/com/jasik/momsnaggingapi/domain/appVersion/controller/AppVersionController.java
  src/main/java/com/jasik/momsnaggingapi/domain/appVersion/repository/AppVersionRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/appVersion/service/AppVersionService.java
  src/main/java/com/jasik/momsnaggingapi/domain/release/controller/ReleaseController.java
  src/main/java/com/jasik/momsnaggingapi/domain/release/repository/ReleaseRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Category.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/ScheduleCategory.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/controller/ScheduleController.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/repository/CategoryRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/repository/ScheduleCategoryRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
  src/main/java/com/jasik/momsnaggingapi/infra/config/AppConfig.java
Labels: documentation, database

#37 feat: bootJar
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: enhancement, setup

#44 35 [feature] Schedule API 작성
  src/main/java/com/jasik/momsnaggingapi/domain/common/BasicResponse.java
  src/main/java/com/jasik/momsnaggingapi/domain/common/CommonResponse.java
  src/main/java/com/jasik/momsnaggingapi/domain/common/ErrorResponse.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Category.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/ScheduleCategory.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/controller/ScheduleController.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/repository/CategoryRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/repository/ScheduleCategoryRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
  src/main/java/com/jasik/momsnaggingapi/infra/config/AsyncConfig.java
Labels: enhancement

#47 [feature] 로그인/회원가입 API 작성
  build.gradle
  src/main/java/com/jasik/momsnaggingapi/domain/auth/exception/LoginFailureException.java
  src/main/java/com/jasik/momsnaggingapi/domain/auth/jwt/authToken.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/User.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/controller/UserController.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/repository/UserRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/service/UserService.java
Labels: enhancement

#54 #39 성적표 API 작성
  src/main/java/com/jasik/momsnaggingapi/domain/grade/Grade.java
  src/main/java/com/jasik/momsnaggingapi/domain/grade/controller/GradeController.java
  src/main/java/com/jasik/momsnaggingapi/domain/grade/repository/GradeRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/grade/service/GradeService.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
Labels: documentation, enhancement

#56 (35,39,40,41) 통합 PR 2
  src/main/java/com/jasik/momsnaggingapi/domain/appVersion/AppVersion.java
  src/main/java/com/jasik/momsnaggingapi/domain/common/BasicResponse.java
  src/main/java/com/jasik/momsnaggingapi/domain/common/CommonResponse.java
  src/main/java/com/jasik/momsnaggingapi/domain/common/ErrorResponse.java
  src/main/java/com/jasik/momsnaggingapi/domain/diary/Diary.java
  src/main/java/com/jasik/momsnaggingapi/domain/diary/controller/DiaryController.java
  src/main/java/com/jasik/momsnaggingapi/domain/grade/Grade.java
  src/main/java/com/jasik/momsnaggingapi/domain/grade/controller/GradeController.java
  src/main/java/com/jasik/momsnaggingapi/domain/grade/service/GradeService.java
  src/main/java/com/jasik/momsnaggingapi/domain/nagging/Nagging.java
  src/main/java/com/jasik/momsnaggingapi/domain/push/Push.java
  src/main/java/com/jasik/momsnaggingapi/domain/question/Question.java
  src/main/java/com/jasik/momsnaggingapi/domain/question/controller/QuestionController.java
  src/main/java/com/jasik/momsnaggingapi/domain/question/service/QuestionService.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Category.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/controller/ScheduleController.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/User.java
  src/main/java/com/jasik/momsnaggingapi/infra/common/AsyncService.java
  src/main/java/com/jasik/momsnaggingapi/infra/common/BaseTime.java
  src/main/java/com/jasik/momsnaggingapi/infra/common/ErrorCode.java
  src/main/java/com/jasik/momsnaggingapi/infra/common/ErrorResponse.java
  src/main/java/com/jasik/momsnaggingapi/infra/common/GlobalExceptionHandler.java
  src/main/java/com/jasik/momsnaggingapi/infra/common/Utils.java
  src/main/java/com/jasik/momsnaggingapi/infra/common/exception/NotValidRoutineException.java
  src/main/java/com/jasik/momsnaggingapi/infra/common/exception/ScheduleNotFoundException.java
  src/main/java/com/jasik/momsnaggingapi/infra/common/exception/ThreadFullException.java
  src/main/java/com/jasik/momsnaggingapi/infra/config/OpenApiConfig.java
Labels: bug, documentation, enhancement

#57 feat: auth & user
  build.gradle
  src/main/java/com/jasik/momsnaggingapi/domain/auth/controller/AuthController.java
  src/main/java/com/jasik/momsnaggingapi/domain/auth/jwt/AuthToken.java
  src/main/java/com/jasik/momsnaggingapi/domain/auth/jwt/AuthTokenProvider.java
  src/main/java/com/jasik/momsnaggingapi/domain/auth/jwt/JwtAuthFilter.java
  src/main/java/com/jasik/momsnaggingapi/domain/auth/jwt/JwtHeaderUtil.java
  src/main/java/com/jasik/momsnaggingapi/domain/auth/service/Authservice.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/User.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/controller/UserController.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/service/UserService.java
  src/main/java/com/jasik/momsnaggingapi/infra/config/SecurityConfig.java
  src/main/java/com/jasik/momsnaggingapi/infra/config/WebConfig.java
  src/main/java/com/jasik/momsnaggingapi/infra/config/auth/SpringSecurityConfig.java
Labels: documentation, enhancement

#58 doc: swagger 접근 권한 수정
  src/main/java/com/jasik/momsnaggingapi/infra/config/SecurityConfig.java
Labels: bug, documentation

#61 Feature/35 feature schedule api add
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/controller/ScheduleController.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/User.java
  src/main/java/com/jasik/momsnaggingapi/infra/common/StringListConverter.java
  src/main/java/com/jasik/momsnaggingapi/infra/config/SecurityConfig.java
Labels: bug, documentation, enhancement

#64 #35 습관 정렬 request 수정
  src/main/java/com/jasik/momsnaggingapi/domain/auth/jwt/AuthTokenProvider.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/controller/ScheduleController.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
Labels: enhancement

#69 68 [feature] 스케줄러 작성
  src/main/java/com/jasik/momsnaggingapi/MomsNaggingApiApplication.java
  src/main/java/com/jasik/momsnaggingapi/domain/diary/controller/DiaryController.java
  src/main/java/com/jasik/momsnaggingapi/domain/diary/service/DiaryService.java
  src/main/java/com/jasik/momsnaggingapi/domain/grade/controller/GradeController.java
  src/main/java/com/jasik/momsnaggingapi/domain/grade/service/GradeService.java
  src/main/java/com/jasik/momsnaggingapi/domain/push/service/FCMService.java
  src/main/java/com/jasik/momsnaggingapi/domain/question/controller/QuestionController.java
  src/main/java/com/jasik/momsnaggingapi/domain/question/service/QuestionService.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/Schedule.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/controller/ScheduleController.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/jasik/momsnaggingapi/domain/schedule/service/ScheduleService.java
  src/main/java/com/jasik/momsnaggingapi/domain/user/User.java
  src/main/java/com/jasik/momsnaggingapi/infra/config/SchedulerConfig.java
Labels: enhancement
